In [8]:
#LIST

aList = ["John", 33,"Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [12]:
#LATIHAN List

import datetime as vDate
tgl_v1 = vDate.date.today()
print(tgl_v1)

hari = tgl_v1.day
tanggal = vDate.date.today()
print(hari)
print(tanggal)

mahasiswa = ["Ranti", "2024072001", "Informatika", "DAA", tanggal, "Universitas Pembangunan Jaya"]
print(mahasiswa)

2025-09-15
15
2025-09-15
['Ranti', '2024072001', 'Informatika', 'DAA', datetime.date(2025, 9, 15), 'Universitas Pembangunan Jaya']


In [21]:
#LATIHAN Lists

from datetime import date

import datetime as vDate
tanggal = vDate.date.today()
print(tanggal.day)
print(tanggal)

mahasiswa = ["Qurratu Farrasah Siregar", "2024071017", "Informatika", "DAA",
             f"{tanggal.day}-{tanggal.month}-{tanggal.year}",
             "Universitas Pembangunan Jaya"]

print(mahasiswa)



15
2025-09-15
['Qurratu Farrasah Siregar', '2024071017', 'Informatika', 'DAA', '15-9-2025', 'Universitas Pembangunan Jaya']


In [17]:
print("NIM :", mahasiswa[1])

NIM : 2024071017


In [18]:
print("Kampus :",mahasiswa[5])

Kampus : Universitas Pembangunan Jaya


In [19]:
print("Mahasiswa :",mahasiswa[1:3])

Mahasiswa : ['2024071017', 'Informatika']


In [22]:
print("Mata Kuliah Tanggal Berapa?", mahasiswa[3:5])

Mata Kuliah Tanggal Berapa? ['DAA', '15-9-2025']


In [75]:
#NESTED TUPLE/BERSARANG

bin_colors=['Red','Green','Blue','Yellow']
bin_colors[0:2]

['Red', 'Green']

In [26]:
bin_colors = ['Red','Green','Blue','Yellow']
for aColor in bin_colors:
    print(aColor + " square ")

Red square 
Green square 
Blue square 
Yellow square 


In [28]:
#LATIHAN Nested Tuple

upj = ("universitas", "pembangunan", "jaya")
print(upj)

nested = (100, (200, 400, 600), 300, (400, 800))
print(nested)

('universitas', 'pembangunan', 'jaya')
(100, (200, 400, 600), 300, (400, 800))


In [30]:
#Dictionary

bin_colors ={
  "manual_color": "Yellow",
  "approved_color": "Green",
  "refused_color": "Red"
}

print(bin_colors)

bin_colors.get('approved_color') #cara 1
bin_colors['approved_color'] #cara 2



{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


'Green'

In [32]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [35]:
# LATIHAN Dictionary

mahasiswa = {
    "Nama": "Qurratu Farrasah Siregar",
    "NIM": "2024071017",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}

print(mahasiswa)

{'Nama': 'Qurratu Farrasah Siregar', 'NIM': '2024071017', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [36]:
mahasiswa.get('Nama')

'Qurratu Farrasah Siregar'

In [37]:
mahasiswa['NIM']

'2024071017'

In [38]:
mahasiswa['Prodi']

'Informatika'

In [39]:
mahasiswa['Universitas']

'UPJ'

In [43]:
# SET

green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [45]:
green = {'grass', 'leaves','leaves'} #jika ada yg lebih dari 2 maka akan diabaikan
print(green)



{'leaves', 'grass'}


In [ ]:
#LATIHAN Sets

yellow = {'dandelions', 'fire hydrant', 'leaves'}
red    = {'rose', 'blood', 'fire hydrant', 'leaves'}

# gabungan (union)
print(yellow | red) #! untuk menggabung semua data yg yg mencakup di lingkaran

# irisan (intersection)
print(yellow & red) #& untuk irisan (yg terkena di tengah)
# {'fire hydrant', 'leaves'}


{'blood', 'rose', 'dandelions', 'fire hydrant', 'leaves'}
{'fire hydrant', 'leaves'}


In [46]:
#DataFrames

import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])

df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [47]:
# Seleksi kolom
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [48]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [49]:
# Row selection
df.iloc[1:3,:]  #yang paling kiri adalah data indeks

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [50]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [51]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [ ]:
# LATIHAN DataFrames

import pandas as pd

mhs = pd.DataFrame([
    [1, 'Informatika',     50, 30, 20],
    [2, 'Sistem Informasi',55, 30, 25],
    [3, 'Teknik Sipil',    40, 30, 10]
])

mhs.columns = ['No', 'Prodi', 'Mahasiswa', 'Laki-laki', 'Perempuan']

print(mhs)





   No             Prodi  Mahasiswa  Laki-laki  Perempuan
0   1       Informatika         50         30         20
1   2  Sistem Informasi         55         30         25
2   3      Teknik Sipil         40         30         10


In [74]:
# MATRIX

import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [73]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [ ]:
#LATIHAN Matrix

import numpy as np
myMatrix = np.array([[100, 200, 300], [700, 800, 500], [900, 1000, 800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  800  500]
 [ 900 1000  800]]


In [53]:
#Transpose Matrix

import numpy as np
myMatrix = np.array([[100, 700, 900], [200, 800, 1000], [300, 500, 800]])
print(myMatrix)

[[ 100  700  900]
 [ 200  800 1000]
 [ 300  500  800]]


In [54]:
#VECTOR
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [72]:
print(type(myVector))

<class 'numpy.ndarray'>


In [71]:
# Menggunakan array numpy:
import numpy as np
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [70]:
print(type(myVector))

<class 'list'>


In [57]:
#STACK

class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [58]:
stack = Stack()
stack.push("Red")
stack.push("Green")
stack.push("Blue")
stack.push("Yellow")

In [59]:
print(stack.pop())

Yellow


In [60]:
print(stack.isEmpty())

False


In [61]:
print(stack.peek())

Blue


In [62]:
print(stack.size())

3


In [63]:
#QUEUE

class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [67]:
queue = Queue()

In [68]:
queue.enqueue("Red")
queue.enqueue("Green")
queue.enqueue("Blue")
queue.enqueue("Yellow")

In [69]:
print(queue.size())

4
